# syntax=docker/dockerfile:1
# Generated by DeepAgent. Rerunning the deploy regenerates this file — delete this line to keep your own edits.
# --- Build stage: all deps so the build (if any) can run ---
# --platform=linux/amd64 forces the same native binaries as the runtime,
# regardless of whether `docker build` runs on a Mac / arm laptop or on
# CI. Without it, a lockfile resolved on darwin-arm64 shipped darwin
# binaries into a linux/amd64 image and the pod crashed on boot loading
# a missing `.node` file (2026-09-29, team-wallet).
FROM --platform=linux/amd64 node:20-bookworm-slim AS builder
WORKDIR /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 make g++ \
    && rm -rf /var/lib/apt/lists/*
COPY package*.json ./
RUN npm pkg delete scripts.prepare scripts.postinstall >/dev/null 2>&1 || true && unset NPM_CONFIG_OMIT && npm install --include=optional --no-audit --no-fund || npm install --include=optional --no-audit --no-fund --legacy-peer-deps
COPY . .
# The repo's own postinstall, now that the files it reads are here
# (no-op when the package.json defines none).
RUN npm run postinstall --if-present
# Prisma: generate the client BEFORE build (no-op without a schema).
RUN if [ -f prisma/schema.prisma ] || [ -f schema.prisma ]; then \
      npx --yes prisma generate; \
    fi
# Auto-build when the app defines a build script (Next.js needs it).
# Fails the image build if the script exists and errors — surfaces bugs early.
# Monorepo awareness: when the root build delegates with `--prefix X`,
# `-w X` or `--workspace X`, install X's deps first — otherwise
# `vite`/`next`/etc live in X/node_modules which `npm install` at the
# root never populated, and the build dies with `sh: vite: not found`.
RUN if node -e "process.exit(require('./package.json').scripts?.build ? 0 : 1)"; then \
      sub=$(node -e "const s=require('./package.json').scripts?.build||''; const m=s.match(/--prefix\s+(\S+)/)||s.match(/-w\s+(\S+)/)||s.match(/--workspace[=\s]+(\S+)/); process.stdout.write(m?m[1]:'')"); \
      if [ -n "$sub" ] && [ -f "$sub/package.json" ]; then \
        echo "monorepo: installing deps for subpackage $sub"; \
        (cd "$sub" && (npm install --no-audit --no-fund --include=optional || npm install --no-audit --no-fund --include=optional --legacy-peer-deps)); \
      fi; \
      npm run build; \
    else \
      echo "no build script — skipping"; \
    fi
# SWC native binding: make the runtime require() need NO cache, EVER.
# Newer @swc/core ships its .node binary compressed and decompresses it
# into a cache directory on first require. The hardened pod cannot offer
# one: HOME is on the read-only layer (EROFS), and the only writable
# mount is a Kubernetes emptyDir at /tmp — mounted 0777 WITHOUT the
# sticky bit, which swc's loader rejects as untrusted ('cache root has a
# parent writable by another user without trusted sticky protection').
# Meanwhile `docker run --tmpfs /tmp:mode=1777` HAS the sticky bit, so
# the CI smoke passed the exact image the pod then crash-looped on
# (2026-09-29, team-wallet, twice). Fix at BUILD time instead: trigger
# the decompression here, where the filesystem is writable, then copy
# the materialized binary next to each binding.js — the loader's FIRST
# strategy, require('./swc.<platform>.node'), a plain require with no
# cache validation at all. chmod 0755 because the materializer writes
# the cache file owner-read-only for ROOT — the runtime uid 1000 got
# 'cannot open shared object file: Permission denied' from the copy
# (2026-09-29, image ac1d525a). The final verification require runs AS
# THE node USER for the same reason: a root-run check reads any file
# and proved nothing. It PROVES each copy loads with no HOME, no cache
# and no root; a repo whose swc cannot load that way fails THIS build,
# not the pod.
RUN set -e;     for d in $(find node_modules -type d -path '*/@swc/core'); do       rm -rf /app/.swc-mat;       XDG_CACHE_HOME=/app/.swc-mat SWC_NATIVE_BINDING_CACHE=/app/.swc-mat         node -e "require(process.argv[1])" "/app/$d" >/dev/null 2>&1 || true;       f=$(find /app/.swc-mat -name '*.node' 2>/dev/null | head -1);       if [ -n "$f" ]; then         cp "$f" "/app/$d/swc.linux-x64-gnu.node";         chmod 0755 "/app/$d/swc.linux-x64-gnu.node";       fi;       rm -rf /app/.swc-mat;       if id -u node >/dev/null 2>&1; then         su -s /bin/sh node -c "HOME=/nonexistent XDG_CACHE_HOME=/nonexistent SWC_NATIVE_BINDING_CACHE=/nonexistent node -e \"require(process.argv[1])\" /app/$d";       else         env HOME=/nonexistent XDG_CACHE_HOME=/nonexistent SWC_NATIVE_BINDING_CACHE=/nonexistent           node -e "require(process.argv[1])" "/app/$d";       fi;     done

# --- Runtime: non-root built-in `node` user ---
FROM --platform=linux/amd64 node:20-bookworm-slim AS runner
ENV NODE_ENV=production
# General caches belong on the pod's one writable mount (the /tmp
# emptyDir; the root filesystem is read-only under the restricted
# profile). The SWC native binding deliberately does NOT rely on this —
# it is baked next to binding.js at build time above, because swc
# refuses any cache under a non-sticky world-writable parent and a
# Kubernetes emptyDir is exactly that.
ENV XDG_CACHE_HOME=/tmp/.cache
WORKDIR /app
# Copy the built app WITH its node_modules from the builder (avoids a second
# install and guarantees framework binaries + build output are present).
COPY --from=builder /app ./
# Numeric uid, not a name. Kubernetes' runAsNonRoot check refuses to start
# a container whose USER is a name: it cannot verify from outside the image
# that the name is non-root, and the pod dies with
# CreateContainerConfigError (2026-09).
# The node images ship 'node' as uid 1000.
USER 1000
EXPOSE 5000
# HEALTHCHECK proves the server is actually listening on its declared port
# BEFORE k8s pulls the image. If the process dies at boot (missing native
# binary, uncaught exception, wrong entrypoint), the local `docker run`
# and the CI smoke step both see UNHEALTHY within seconds and refuse to
# push — the entire "compiles, pushes, CrashLoopBackOff" class stops at
# build time. Uses `node -e` because bookworm-slim ships no curl/wget.
# statusCode < 500 accepts any response the app produces (200, 404,
# 302 …) — the point is "the process answers TCP + HTTP", not that a
# specific route returns 200. That route check belongs to the K8s
# readiness probe, which asks the app-defined path.
HEALTHCHECK --interval=15s --timeout=5s --start-period=20s --retries=3 \
    CMD node -e "require('http').get('http://127.0.0.1:5000/', r => process.exit(r.statusCode < 500 ? 0 : 1)).on('error', () => process.exit(1))"
CMD ["sh", "-c", "export PATH=/app/node_modules/.bin:$PATH; exec node app.js"]
